name: Build and Deploy Javadoc

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: gradle build shadowJar

      - name: Generate Javadoc
        run: gradle javadoc

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-assets
          path: build/libs/*.jar
          archive: false

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/docs/javadoc'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
